name: Build & Release Installer

on:
  push:
    tags:
      - 'v*'  # Triggers on tag push like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Build and package
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: pyinstaller ORMTexturePacker.spec

    - name: Install Inno Setup
      run: |
        choco install innosetup -y

    - name: Create Installer with Inno Setup
      run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_script.iss'

    - name: Upload Installer as Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Output/setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
