name: Build & Release Installer

on:
  push:
    tags:
      - 'v*'  # Trigger on tag push like v1.0.0
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Grants permission to create releases

jobs:
  build:
    name: Build and Package
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller ORMTexturePacker.spec

      - name: Verify EXE file exists
        run: |
          if (Test-Path "dist\ORMTexturePacker.exe") {
            Write-Host "EXE found: dist\ORMTexturePacker.exe"
          } else {
            Write-Error "EXE NOT found!"
            exit 1
          }
        shell: pwsh

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build installer with Inno Setup
        shell: pwsh
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer_script.iss

      - name: Verify installer output file exists
        run: |
          if (Test-Path "Output\ORMTexturePackerInstaller.exe") {
            Write-Host "Installer found: Output\ORMTexturePackerInstaller.exe"
          } else {
            Write-Error "Installer NOT found!"
            exit 1
          }
        shell: pwsh

      - name: Check if release exists
        id: check_release
        shell: bash
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          if gh release view "$TAG_NAME" &>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Installer as Release Asset
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          files: Output/ORMTexturePackerInstaller.exe
          body: |
            **Links**
            - [Changelog](https://github.com/Sergey-Russiyan/ORM_Packer/blob/main/CHANGELOG.md)
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
